= IDN Catalogue Profile

This repository contains the https://mspgh.unimelb.edu.au/centres-institutes/centre-for-health-equity/research-group/indigenous-data-network[Indigenous Data Network (IDN)]'s profile of https://www.w3.org/TR/vocab-dcat/[the Data Catalog Vocabulary (DCAT)] which is a metadata model for describing datasets.

For all details, see this Profile's main defining document which is in this repository (profile.html) but rendered online at it's persistent web location:

* **http://w3id.org/idn/def/cp**


== License & Rights

The contents of this repository is licensed under Creative Commons 4.0 International. See the LICENSE file in the repository for details.

All content is &copy; Indigenous Data Network, 2022

== Contacts

Initial technical development of this work is being undertaken by the following, for the Indigenous Data Network:

**Nicholas J. Car** +
*Data Architect* +
https://kurrawong.net[Kurrawong AI] +
nick@kurrawong.net  

**Sandra Silcot** +
*Analyst* +
University of Melbourne +
Indigenous Data Network +
