= IDN Catalogue Profile

This repository contains the https://mspgh.unimelb.edu.au/centres-institutes/centre-for-health-equity/research-group/indigenous-data-network[Indigenous Data Network (IDN)]'s _Profile_ of the https://www.w3.org/TR/vocab-dcat/[Data Catalog Vocabulary (DCAT)], the https://www.w3.org/TR/prov-o/[Provenance Ontology (PROV-O)] and some other well-known https://www.w3.org/standards/semanticweb/[Semantic Web] information models used for describing catalogued resources.

This Profile's main defining document which is in this repository (profile.html) is rendered online at its persistent web location:

* **https://data.idnau.org/pid/cp**

That document contains a list of the various resources provided by this profile, most of which are stored in this repository within the `rd/` folder.

== License & Rights

The contents of this repository is licensed under Creative Commons 4.0 International. See the LICENSE file in the repository for details.

All content is &copy; Indigenous Data Network, 2022

== Contacts

Initial technical development of this work is being undertaken by the following, for the Indigenous Data Network:

**Nicholas J. Car** +
*Data Architect* +
https://kurrawong.ai[KurrawongAI] +
nick@kurrawong.net  

**Sandra Silcot** +
*Analyst* +
University of Melbourne +
Indigenous Data Network +
