= IDN CP Calculators

The Python files in this folder calculate FAIR, CARE scores and the requirements for LC Labels for datasets based on IDN CP metadata.

Individual FAIR, CARE & LC Labels assessments are performed in the _idncp_fair.py_ and similar files and the file _calc.py_ imports them and can be used to run any of them.

The Python dependencies for these scripts are given in the file _pyproject.toml_ in this folder which is expected to be used with Python's https://python-poetry.org/[Poetry] too for environment establishment.

== Calculator logic

The logic used to generate scored or requirement for labels is given within comments in the script files. The logic is based on IDN deliberations and may be published in a more human-readable form when a complete first version of the scripts is working.

== Use

These Python scripts calculate their various scores from input metadata. In addition to looking for metadata elements, they also look up additional details for values they see online, in particular they attempt to ascertain the indigeneity of `Agents` associate with a `Dataset` by looking up the `Agent` online, in the http://idn.kurrawong.net[IDN Agent Catalogue] which contains indigeneity notes.

To use the scripts via _calc.py_, you need to run them as a Python command line program:

`~$ python calc.py ...`

You need to indicate the calculation being performed - "fair", "care" or "lc" and to indicate the source of the metadata to be assessed - a file or online location. You can optionally tell the script how to return results, rather than just printing them to screen. the formal command line arguments are:

